language: java
addons:
  apt:
    packages:
    - xvfb
    - chromium-browser
install: true
script: mvn -B install -Pcrx-xvfb-run -Dantiprint.chrome.extraArgs=--no-sandbox -Dantiprint.chrome.executablePath=/usr/bin/chromium-browser
