language: java
addons:
  apt:
    packages:
    - xvfb
    - chromium-browser
    - firefox
notifications:
  email: false
install: ip addr
script: mvn -B install -Dantiprint.chrome.extraArgs=--no-sandbox -Dwdm.gitHubTokenName=$GITHUB_TOKEN_NAME -Dwdm.gitHubTokenSecret=$GITHUB_TOKEN_SECRET
