language: java
jdk: openjdk11
addons:
  apt:
    packages:
    - xvfb
    - chromium-browser
    - firefox
notifications:
  email: false
before_install: dpkg-query -l google-chrome-stable || true
install: dpkg-query -l xvfb chromium-browser firefox
before_script: which firefox && firefox --version
script: mvn --batch-mode $MAVEN_OPTIONS install -Dantiprint.chrome.extraArgs=--no-sandbox -Dwdm.gitHubTokenName=$GITHUB_TOKEN_NAME -Dwdm.gitHubTokenSecret=$GITHUB_TOKEN_SECRET -Dwebdriver.firefox.bin=/usr/bin/firefox -Dwdm.chromeDriverVersion=$CHROMEDRIVER_VERSION -Dwdm.geckoDriverVersion=$GECKODRIVER_VERSION
