language: java
addons:
  apt:
    packages:
    - xvfb
    - chromium-browser
    - firefox
notifications:
  email: false
install: ip addr
script: mvn -B install -Pcrx-xvfb-run -Dantiprint.chrome.extraArgs=--no-sandbox -Dantiprint.chrome.executablePath=/usr/bin/chromium-browser -Dwdm.gitHubTokenName=$GITHUB_TOKEN_NAME -Dwdm.gitHubTokenSecret=$GITHUB_TOKEN_SECRET
