version: "{build}"
image: Visual Studio 2017
build_script:
- cmd: >-
    set JAVA_HOME=C:\Program Files\Java\jdk1.8.0

    mvn --version

    echo "environment: GITHUB_TOKEN_NAME=%GITHUB_TOKEN_NAME%"

    echo "environment: CHROMEDRIVER_VERSION=%CHROMEDRIVER_VERSION%"

    mvn install --quiet --batch-mode -Dopenssl.tests.skip=true -Dwdm.gitHubTokenName=%GITHUB_TOKEN_NAME% -Dwdm.gitHubTokenSecret=%GITHUB_TOKEN_SECRET% -Dantiprint.chromedriver.version=%CHROMEDRIVER_VERSION%
